---
- name: provision the ec2
  hosts: testgroup
  tasks:
    - name: Update all packages on the slave
      apt:
        update_cache: yes
      become: yes

    - name: Install some components
        shell: |
          apt install git -y
          apt install openjdk-8-jdk -y
          apt install maven -y
        become: yes

    - name: Check that mysql is enabled and running
      service:
        name: mysql
        enabled: true
        state: started
      become: yes

    - name: Clone a github repository
      git:
        repo: https://github.com/smoha020/book-world.git
        dest: /home/ubuntu/repos/
        clone: yes
        update: yes
      become: yes

    - name: Prepare jar file
      shell: |
        cd /home/ubuntu/repos/demo/ && mvn clean install
        cd /home/ubuntu/repos/demo/target && nohup java -jar demo-0.0.1-SNAPSHOT.jar &
      become: yes